require("rodzee.plugins-setup")

require("rodzee.core.options")
require("rodzee.core.keymaps")
require("rodzee.core.colorscheme")
require("rodzee.plugins.comment")
require("rodzee.plugins.nvim-tree")
require("rodzee.plugins.nvim-cmp")
require("rodzee.plugins.lualine")
require("rodzee.plugins.telescope")
require("rodzee.plugins.lsp.mason")
require("rodzee.plugins.lsp.lspsaga")
require("rodzee.plugins.lsp.lspconfig")
require("rodzee.plugins.lsp.null-ls")
require("rodzee.plugins.autopairs")
require("rodzee.plugins.treesitter")
require("rodzee.plugins.gitsigns")
